export const sampleItems: ItemType[] = [
  {
    id: "1",
    name: "Chicken Thigh",
    fromDealer: "MT Barker",
    shelfCount: 5,
    stockCount: 10,
    reducedCount: 2,
    totalCount: 17,
    shelfCapacity: "2/4",
    toOrderCount: 3,
  },
  {
    id: "2",
    name: "Beef Mince",
    fromDealer: "Jazella",
    shelfCount: 3,
    stockCount: 7,
    reducedCount: 1,
    totalCount: 11,
    shelfCapacity: "3/5",
    toOrderCount: 4,
  },
  {
    id: "3",
    name: "Pork Belly",
    from: "Sunrise Meats",
    shelfCount: 4,
    stockCount: 5,
    reducedCount: 0,
    totalCount: 9,
    shelfCapacity: "4/6",
    toOrderCount: 2,
  },
  {
    id: "4",
    name: "Lamb Chops",
    from: "Farm Fresh",
    shelfCount: 6,
    stockCount: 4,
    reducedCount: 2,
    totalCount: 12,
    shelfCapacity: "6/8",
    toOrderCount: 0,
  },
  {
    id: "5",
    name: "Whole Chicken",
    from: "Birds & Co.",
    shelfCount: 2,
    stockCount: 8,
    reducedCount: 1,
    totalCount: 11,
    shelfCapacity: "2/3",
    toOrderCount: 1,
  },
];
